locallibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('books/', views.BookListView.as_view(), name='books'),
	path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
	path('book/<int:pk>/review',views.review_book,name='review-book'),
	path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('searchB/',views.SearchBook, name='searchB'),
    path('searchA', views.SearchAuthor, name='searchA')
]

locallibrary/locallibrary/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('schedule/', include('schedule.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User 
import datetime,random, string
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")
    
    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    def get_image_name(instance, filename):
        fn = '%s.jpg' %''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(5))
        return fn


    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    image = models.ImageField(upload_to = get_image_name, null=True,blank=True)

    

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title
    
    
    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this book.
        """
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
    display_genre.short_description = 'Genre'    
	

class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    class Meta:
        ordering = ["due_back"]
        

    def __str__(self):
        """
        String for representing the Model object
        """
        return '{0} ({1})'.format(self.id,self.book.title)

    @property
    def is_overdued(self):
    	if self.due_back and date.today() > self.due_back:
    		return True
    	return False

class Author(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ["last_name","first_name"]
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])
    

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '{0}, {1}'.format(self.last_name,self.first_name)

class Review(models.Model):
    review = models.CharField(max_length=100)
    star = models.IntegerField(default=5, 
    validators = [MaxValueValidator(5),MinValueValidator(1)])
    date = models.DateField(editable=False,default=datetime.date.today)
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
    def __str__(self):
        return self.review

    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this book.
        """
        return reverse('review-book')

locallibrary/catalog/forms.py
from django import forms
from .models import Book
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime
from django.views import generic

class ReviewBookForm(forms.Form, generic.DetailView):
	model = Book
	new_review = forms.CharField(help_text="Enter review for this book")
	new_star = forms.IntegerField()
	def clean_review(self):
		data = self.cleaned_data['new_review']
		data_star = self.cleaned_data['new_star']
		if len(data)==0:
			raise ValidationError(_('Write something before submit'))

		if len(data)>100:
			raise ValidationError(_('Please write in less than 100 words'))

		return data

locallibrary/catalog/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Book, Author, BookInstance, Genre, Review
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
from .forms import ReviewBookForm

# Create your views here.

def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    # Available books (status = 'a')
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()  # The 'all()' is implied by default.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1


    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={'num_books':num_books,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_authors':num_authors,'num_visits':num_visits},
    )

class BookListView(generic.ListView):
    model = Book

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """
    Generic class-based view listing books on loan to current user. 
    """
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


def review_book(request, pk):

    if request.method == 'POST':
        form = ReviewBookForm(request.POST)

        if form.is_valid():
            review_inst = Review()
            book_inst = get_object_or_404(Book, pk=pk)
            review_inst.review = form.cleaned_data['new_review']
            review_inst.book = book_inst
            
            review_inst.save()

            return HttpResponseRedirect(reverse('books'))

    else:
        form = ReviewBookForm()

    return render(request, 'catalog/book_review.html', {'form': form,})


def SearchBook(request):
    template = 'catalog/search_booklist.html'
    query = request.GET.get('q','')
    results = Book.objects.filter(title__icontains=query)
    context = {
    'items' : results
    }
    return render( request, template, context)

def SearchAuthor(request):
    template = 'catalog/search_author.html'
    query = request.GET.get('q','')
    results = Author.objects.filter(Q(first_name__icontains=query) | Q(last_name__icontains=query))
    context = {
    'items' : results
    }
    return render(request, template, context)







# def like_book(request, pk):
#     if request.method == 'POST':
#         book_inst = get_object_or_404(Book, pk=pk)
#         book.like = book.like+1
#         return HttpResponseRedirect(reverse('books'))

# def dislike_book(request,pk):
#     if request.method == 'POST':
#         book_inst = get_object_or_404(Book, pk=pk)
#         book.dislike = book.dislike+1
#         return HttpResponseRedirect(reverse('books'))

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}




<header class="jumbotron">
        <div class="container">
            <h1>{{author}}</h1>
        </div>
    </header>

<div class="container">
  <div class="row row-content ">
    
    <div class="col-12 col-sm-6 col-md-8 col-lg-9 ">
        
        <div class="row row-content">
            <div class="col-5 col-sm-3 col-md-2 col-lg-1 align-self-center" style="text-align: right"><span class="fa fa-info fa-3x"></span></div>
            <div class="col-7 col-sm-10">
                <h1>Details</h1>
            </div>
        </div>
        <hr>
        <div class="row row-content">
            <div class="col-sm-1"></div>
            <div class="col-sm-11">
                
                <p><strong>Date of Birth: </strong>
                    {%if author.date_of_birth %}
                        {{author.date_of_birth}}
                    {% else %}
                        Not Specified
                    {% endif %}
                </p>
                <p><strong>Till: </strong>
                    {%if author.date_of_death %}
                        {{author.date_of_death}}
                    {% else %}
                        Not Specified
                    {% endif %}
                </p>
                
            </div>
        </div>
        <br><br>
        <div class="row row-content">
             <div class="col-5 col-sm-3 col-md-2 col-lg-1 align-self-center" style="text-align: right"><span class="fa fa-book fa-3x"></span></div>
            <div class="col-sm-6 mr-auto">
                <h1>Books</h1>
                
            </div>
        </div>
        <hr>
      
        
        <div class="row row-content">
            <div class="col-5 col-sm-3 col-md-2 col-lg-1" ></div>
            <div class="col-sm-6">
                {% if author.book_set.all %}
                    {% for book in author.book_set.all %}
                    <h5>
                        <a href="{% url 'book-detail' book.pk %}">{{book}}</a>  ({{book.bookinstance_set.all.count}})
                    </h5>
                    <p>{{book.summary}}</p>
                    {% endfor %}
                {% else %}
                    <p>There are no Books.</p>
                {% endif %} 
            </div>
        </div>
        
        
        
      </div> 
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 flex-first flex-sm-last">
          <div class="card">
                {% load static %}
                <img class="card-img-top" src="{% static 'media_cdn/defaultAuthor.png' %}" height="250" style="padding: 20px;">
                </div>
          <h5 style="text-align: center;">Author</h5>
          <br>
      </div>
    </div>
  </div>  



{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}

<header class="jumbotron">
        <div class="container">
            <div class="row row-header">
                <div class="col-12 col-md-6">
                    <form method="GET" action="{% url 'searchA' %}">
                    <div class="input-group mb-3">
                        
                          <input type="text"  name="q" autocomplete="off" value="{{request.GET.q}}" class="form-control" placeholder="Search Authors" aria-label="Search" aria-describedby="basic-addon2">
                          <div class="input-group-append">
                            <button class="btn btn-success" type="submit"><span class="fa fa-search fa-lg"></span></button>
                          </div>
                        
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </header>

<div class="container">
    <h1>Author List</h1>
    
    <div class="row">
        {% if author_list %}
        
        {% for author in author_list %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3">
            <div class="card">
                <div class="card-body" style="padding: 20px;text-align: center;">
                    <h4 class="card-title">{{ author.first_name }}</h4>
                    <p class="card-body">{{author.last_name}}, {{author.first_name}}</p>
                    <a href="{{ author.get_absolute_url }}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}

    {% else %}
      <p>There are no authors in the library.</p>
    {% endif %} 
    </div>
    
</div>
<br><br>


   
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}

<header class="jumbotron">
        <div class="container">
            <h1>{{book.title}}</h1>
        </div>
    </header>

<div class="container">
  <div class="row row-content ">
    
    <div class="col-12 col-sm-6 col-md-8 col-lg-9 ">
        
        <div class="row row-content">
            <div class="col-5 col-sm-3 col-md-2 col-lg-1 align-self-center" style="text-align: right"><span class="fa fa-book fa-3x"></span></div>
            <div class="col-7 col-sm-10">
                <h1>Details</h1>
            </div>
        </div>
        <hr>
        <div class="row row-content">
            <div class="col-sm-1"></div>
            <div class="col-sm-11">
                <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
                <p><strong>Summary:</strong> {{ book.summary }}</p>
                <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
                <p><strong>Language:</strong> {{ book.language }}</p>  
                <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

                <div style="margin-top:30px;">
                  <h4>Copies</h4>

                  {% for copy in book.bookinstance_set.all %}
                  <hr>
                  <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
                  {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
                  <p><strong>Imprint:</strong> {{copy.imprint}}</p>
                  <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
                  {% endfor %}
                </div>
            </div>
        </div>
        <br><br>
        <div class="row row-content">
             <div class="col-5 col-sm-3 col-md-2 col-lg-1 align-self-center" style="text-align: right"><span class="fa fa-comments fa-3x"></span></div>
            <div class="col-sm-6 mr-auto">
                <h1>Reviews</h1>
                
            </div>
            <div class=" ml-auto align-self-center">
                    {% if user.is_authenticated %}
                      <a href="{% url 'review-book' book.pk %}"><span class="fa fa-plus"></span> Write Review</a>
                    {% endif %}
                
            </div>
        </div>
        <hr>
      
        
        <div class="row row-content">
            <div class="col-5 col-sm-3 col-md-2 col-lg-1" ></div>
            <div class="col-sm-6">
                {% if book.review_set.all %}
                    {% for review in book.review_set.all %}
                    <h5>{{star}} <span class="fa fa-star"></span> {{review}}</h5>
                    <p>--{{review.date}}</p>
                    {% endfor %}
                {% else %}
                    <p>There are no reviews.
                    {% if user.is_authenticated %} 
                        Be the first to
                      <a href="{% url 'review-book' book.pk %}"> write a review</a></p>
                    {% endif %}
                {% endif %} 
            </div>
        </div>
        
        
        
      </div> 
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 flex-first flex-sm-last">
          <div class="card">
                {% load static %}
                <img class="card-img-top" src="{{ book.image.url }}" height="250" style="padding: 20px;">
                </div>
          <h5 style="text-align: center;">Book Image</h5>
          <br>
      </div>
    </div>
  </div>  



{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}

<header class="jumbotron">
        <div class="container">
            <div class="row row-header">
                <div class="col-12 col-md-6">
                    <form method="GET" action="{% url 'searchB' %}">
                    <div class="input-group mb-3">
                        
                          <input type="text"  name="q" autocomplete="off" value="{{request.GET.q}}" class="form-control" placeholder="Search Book" aria-label="Search" aria-describedby="basic-addon2">
                          <div class="input-group-append">
                            <button class="btn btn-success" type="submit"><span class="fa fa-search fa-lg"></span></button>
                          </div>
                        
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </header>

<div class="container">
    <h1>Book List</h1>
    
    <div class="row">
        {% if book_list %}
        
        {% for book in book_list %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3">
            <div class="card">
                {% load static %}
                <img class="card-img-top" src="{{ book.image.url }}" height="250" style="padding: 20px;">
                <div class="card-body" style="padding: 20px;">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <p class="card-text">({{book.author}})</p>
                    <a href="{{ book.get_absolute_url }}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}

    {% else %}
      <p>There are no books in the library.</p>
    {% endif %} 
    </div>
    
</div>
<br><br>
       
{% endblock %}

locallibrary/catalog/templates/catalog/book_review.html
{% extends "base_generic.html" %}
{% block content %}
	{% if user.is_authenticated %}
        <form action="" method="POST">
			{% csrf_token %}
			<table>
				{{ form }}
			</table>
			<input type="submit" value="submit" />
		</form>  
    {% else %}
    	<li>Please <a href="{% url 'login'%}?next={{request.path}}">Login</a> to submit a review.</li>
    {% endif %}
	
{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    

<header class="jumbotron">
        <div class="container">
            <h1>Borrowed books</h1>
        </div>
</header>

<div class="container">
    <h1><span class="fa fa-book"></span> Book List</h1>
    
    <div class="row">
        {% if bookinstance_list %}
        
        {% for bookinst in bookinstance_list %} 
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3">
            <div class="card">
                {% load static %}
                <img class="card-img-top" src="{{ bookinst.book.image.url }}" height="250" style="padding: 20px;">
                <div class="card-body" style="padding: 20px;">
                    <h5 class="card-title">{{ bookinst.book.title }}</h5>
                    <p class="card-text">({{bookinst.book.author}})</p>
                    <p class="card-text"><strong>Due Back: </strong>{{bookinst.due_back}}</p>
                    <a href="{{ bookinst.book.get_absolute_url }}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}

    {% else %}
      <p>There are no borrowed books.</p>
    {% endif %} 
    </div>
    
</div>

{% endblock %}

locallibrary/catalog/templates/catalog/search_author.html
{% extends "base_generic.html" %}
{% block content %}
	
<header class="jumbotron">
        <div class="container">
            <div class="row row-header">
                <div class="col-12 col-md-6">
                    <form method="GET" action="{% url 'searchA' %}">
                    <div class="input-group mb-3">
                        
                          <input type="text"  name="q" autocomplete="off" value="{{request.GET.q}}" class="form-control" placeholder="Search Authors" aria-label="Search" aria-describedby="basic-addon2">
                          <div class="input-group-append">
                            <button class="btn btn-success" type="submit"><span class="fa fa-search fa-lg"></span></button>
                          </div>
                        
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </header>

<div class="container">
    <h1>Author List</h1>
    <p>Search list with query {{request.GET.q}}</p>
    <div class="row">
        {% if items %}
        
        {% for author in items %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3">
            <div class="card">
                <div class="card-body" style="padding: 20px;text-align: center;">
                    <h4 class="card-title">{{ author.first_name }}</h4>
                    <p class="card-body">{{author.last_name}}, {{author.first_name}}</p>
                    <a href="{{ author.get_absolute_url }}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}

    {% else %}
      <p>There are no authors in the library.</p>
    {% endif %} 
    </div>
    
</div>
<br><br>


   
{% endblock %}

locallibrary/catalog/templates/catalog/search_booklist.html
{% extends "base_generic.html" %}
{% block content %}

<header class="jumbotron">
        <div class="container">
            <div class="row row-header">
                <div class="col-12 col-md-6">
                    <form method="GET" action="{% url 'searchB' %}">
                    <div class="input-group mb-3">
                        
                          <input type="text"  name="q" autocomplete="off" value="{{request.GET.q}}" class="form-control" placeholder="Search Book" aria-label="Search" aria-describedby="basic-addon2">
                          <div class="input-group-append">
                            <button class="btn btn-success" type="submit"><span class="fa fa-search fa-lg"></span></button>
                          </div>
                        
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </header>

<div class="container">
    <h1>Book List</h1><p>Search list with query {{request.GET.q}}</p>
    
    <div class="row">
        {% if items %}
        
        {% for book in items %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3">
            <div class="card">
                {% load static %}
                <img class="card-img-top" src="{{ book.image.url }}" height="250" style="padding: 20px;">
                <div class="card-body" style="padding: 20px;">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <p class="card-text">({{book.author}})</p>
                    <a href="{{ book.get_absolute_url }}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}

    {% else %}
      <p>There are no books in the library.</p>
    {% endif %} 
    </div>
    
</div>
<br><br>
       
{% endblock %}